import { PGlite } from "@electric-sql/pglite";
import { getTableConfig, type PgTable } from "drizzle-orm/pg-core";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { readSchemaSnapshot } from "./testing.js";
import * as schema from "./schema.all.js";

/**
 * Every modelled column agrees with the deployed one about NULL.
 *
 * `drift.test.ts` compares column NAMES and TYPES. It does not compare
 * nullability, and that gap has cost real time: a column declared nullable
 * when the table says NOT NULL makes an insert that omits it TYPE-CHECK and
 * then fail at the driver, with an error that names a constraint rather than
 * the line that forgot the field. Three separate defects in one migration
 * session were that exact shape.
 *
 * The two directions are not symmetric, so they are checked separately:
 *
 *   TOO LOOSE — the table says NOT NULL and the model does not. This is the
 *   dangerous one. The compiler permits an insert the database refuses, so it
 *   is found at runtime, by whoever happens to run that path first.
 *
 *   TOO STRICT — the table allows NULL and the model says otherwise. Harmless
 *   at runtime and still worth knowing: it makes callers supply a value the
 *   database would have been happy without, and it usually means the model was
 *   written from an intention rather than from the schema.
 *
 * The snapshot is the deployed schema, generated by `db:snapshot` from a real
 * database, so this compares the models against production's own answer rather
 * than against another declaration of the same thing.
 */

let deployed: Map<string, { notNull: boolean; hasDefault: boolean }>;
let pg: PGlite;

beforeAll(async () => {
  pg = new PGlite();
  await pg.exec(readSchemaSnapshot());
  const { rows } = await pg.query<{
    table_name: string;
    column_name: string;
    is_nullable: string;
    column_default: string | null;
  }>(
    `SELECT table_name, column_name, is_nullable, column_default
       FROM information_schema.columns
      WHERE table_schema = 'public'`,
  );
  deployed = new Map(
    rows.map((row) => [
      `${row.table_name}.${row.column_name}`,
      { notNull: row.is_nullable === "NO", hasDefault: row.column_default !== null },
    ]),
  );
}, 60_000);

afterAll(async () => {
  await pg.close();
});

interface Mismatch {
  column: string;
  table: string;
  database: string;
  declared: string;
}

/** Every column of every modelled table, paired with what the database says. */
function compare(): { tooLoose: Mismatch[]; tooStrict: Mismatch[] } {
  const tooLoose: Mismatch[] = [];
  const tooStrict: Mismatch[] = [];

  for (const [exportName, candidate] of Object.entries(schema)) {
    let config;
    try {
      config = getTableConfig(candidate as PgTable);
    } catch {
      // Not a table — the module also exports enums, types and helpers.
      continue;
    }

    for (const column of config.columns) {
      const key = `${config.name}.${column.name}`;
      const actual = deployed.get(key);
      // A table or column the snapshot does not have is `drift.test.ts`'s
      // business, not this one's. Reporting it here would say the same thing
      // twice in two vocabularies.
      if (!actual) continue;

      if (actual.notNull && !column.notNull) {
        tooLoose.push({
          column: key,
          table: exportName,
          database: "NOT NULL",
          declared: "nullable",
        });
      } else if (!actual.notNull && column.notNull && !column.hasDefault) {
        tooStrict.push({
          column: key,
          table: exportName,
          database: "nullable",
          declared: "NOT NULL",
        });
      }
    }
  }

  return { tooLoose, tooStrict };
}

const render = (items: Mismatch[]): string =>
  items.map((m) => `  ${m.column} — database ${m.database}, model ${m.declared} (${m.table})`).join("\n");

describe("modelled nullability matches the deployed schema", () => {
  it("declares NOT NULL wherever the table does", () => {
    // The dangerous direction: the compiler permits an insert the database
    // refuses, so it is found at runtime by whoever runs that path first.
    const { tooLoose } = compare();
    expect(
      tooLoose,
      tooLoose.length === 0
        ? ""
        : `These columns are NOT NULL in the database and nullable in the model.\n` +
          `An insert that omits one type-checks and fails at the driver:\n${render(tooLoose)}`,
    ).toEqual([]);
  });

  it("does not demand a value the table would accept without", () => {
    // Harmless at runtime, and still worth knowing: it makes callers supply
    // something the database was happy without, and usually means the model
    // was written from an intention rather than from the schema.
    const { tooStrict } = compare();
    expect(
      tooStrict,
      tooStrict.length === 0
        ? ""
        : `These columns are nullable in the database and NOT NULL in the model,\n` +
          `with no default to fill them:\n${render(tooStrict)}`,
    ).toEqual([]);
  });

  it("actually looked at something", () => {
    // A guard that silently compares nothing passes forever. If the export
    // shape changes and `getTableConfig` starts throwing for everything, this
    // is what says so.
    let tables = 0;
    for (const candidate of Object.values(schema)) {
      try {
        getTableConfig(candidate as PgTable);
        tables += 1;
      } catch {
        /* not a table */
      }
    }
    expect(tables).toBeGreaterThan(40);
    expect(deployed.size).toBeGreaterThan(200);
  });
});
