import { randomUUID } from "node:crypto";
import { PGlite } from "@electric-sql/pglite";
import { drizzle } from "drizzle-orm/pglite";
import express from "express";
import type { NextFunction, Request, Response } from "express";
import request from "supertest";
import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { createSchemaDb, schema, type Db } from "@datahub/db";
import type { SessionUser } from "@datahub/contracts";
import { createUploadsModule } from "./index.js";


const BROKER: SessionUser = {
  id: "11111111-1111-1111-1111-111111111111",
  name: "Broker",
  email: "broker@example.com",
  role: "broker",
  company_id: null,
  status: "active",
  company_ids: [],
};

/** Collect a binary response body into a Buffer. */
/** Superagent's response, not Express's — same name, different type. */
function binaryParser(res: NodeJS.EventEmitter, cb: (err: Error | null, body: Buffer) => void) {
  const chunks: Buffer[] = [];
  res.on("data", (c: Buffer) => chunks.push(Buffer.from(c)));
  res.on("end", () => cb(null, Buffer.concat(chunks)));
}

let client: PGlite;
let db: Db;
let app: express.Express;
let current: SessionUser;
let folderId: string;

beforeEach(async () => {
  // The real deployed schema, generated by packages/db/scripts/snapshot-schema.mjs.
  // Nothing here declares a table, so nothing here can declare one wrongly.
  client = await createSchemaDb();
  db = drizzle(client, { schema }) as unknown as Db;
  const companyId = randomUUID();
  // `industry` is NOT NULL with no default in the deployed schema. The fixture
  // has to satisfy the same constraints the API does — which is the whole point
  // of loading the real schema rather than a convenient approximation.
  await db.insert(schema.companies).values({ id: companyId, name: "Acme", industry: "" });
  // folders.created_by is a real foreign key to users. The hand-written DDL
  // declared it as a bare uuid, so tests could reference a user that did not
  // exist — another way the old fixtures were easier to satisfy than production.
  await db.insert(schema.users).values({
    id: BROKER.id, name: BROKER.name, email: `${BROKER.id}@x.test`,
    passwordHash: "x", role: "broker", companyId,
  });
  folderId = randomUUID();
  await db.insert(schema.folders).values({ id: folderId, companyId, name: "Finance", createdBy: BROKER.id });
  current = { ...BROKER, company_ids: [companyId] };

  const requireAuth = (req: Request, _res: Response, next: NextFunction) => {
    req.user = current;
    next();
  };
  app = express();
  app.use("/", createUploadsModule({ db, requireAuth }).router);
});

afterEach(async () => {
  await client.close();
});

describe("uploads router — blob round-trip through bytea (real Postgres)", () => {
  it("stores raw bytes and streams the identical bytes + content-type back", async () => {
    const payload = Buffer.from([0, 1, 2, 3, 255, 254, 100, 42]);
    const up = await request(app)
      .post("/uploads")
      .set("Content-Type", "application/octet-stream")
      .set("x-file-name", "blob.bin")
      .send(payload);
    expect(up.status).toBe(201);
    expect(up.body.size_bytes).toBe(payload.length);

    const got = await request(app).get(`/uploads/${up.body.id}/content`).buffer(true).parse(binaryParser as unknown as (res: unknown, cb: (err: Error | null, body: unknown) => void) => void);
    expect(got.status).toBe(200);
    expect(got.headers["content-type"]).toContain("application/octet-stream");
    expect(Buffer.compare(got.body, payload)).toBe(0);

    // The bytes really live in the uploads table.
    expect((await db.select().from(schema.uploads)).length).toBe(1);
  });

  it("404s content for an unknown upload id", async () => {
    expect((await request(app).get(`/uploads/${randomUUID()}/content`)).status).toBe(404);
  });
});

describe("uploads router — documents under a folder (real Postgres)", () => {
  /** A document in the beforeEach folder, via the real upload → document path. */
  async function seedDocument(): Promise<string> {
    const up = (await request(app).post("/uploads")
      .set("Content-Type", "application/pdf").set("x-file-name", "lease.pdf")
      .send(Buffer.from("pdf"))).body;
    const doc = await request(app).post(`/folders/${folderId}/documents`)
      .send({ name: "Lease.pdf", upload_id: up.id, size: "3", ext: "pdf" });
    expect(doc.status).toBe(201);
    return doc.body.id as string;
  }

  it("records an activity row both engines can read", async () => {
    // The regression this file exists to prevent from recurring: writing only
    // the module's columns leaves legacy's NOT NULL ones empty, and every
    // POST /documents/:id/activity 500s while the GET keeps returning a
    // healthy-looking empty list.
    const documentId = await seedDocument();

    await request(app).post(`/documents/${documentId}/activity`).send({ action: "view" }).expect(201);

    const listed = await request(app).get(`/documents/${documentId}/activity`);
    expect(listed.body).toHaveLength(1);
    expect(listed.body[0]).toMatchObject({ action: "view", document_id: documentId });

    // Legacy reads its own columns off the same row. One row, both vocabularies.
    const legacyView = await client.query<{ user_id: string; activity_type: string }>(
      `SELECT user_id, activity_type FROM document_activity WHERE document_id = $1`,
      [documentId],
    );
    expect(legacyView.rows[0]).toMatchObject({ activity_type: "view", user_id: BROKER.id });
  });

  it("refuses an action the deployed enum cannot store, at the edge", async () => {
    const documentId = await seedDocument();

    const res = await request(app)
      .post(`/documents/${documentId}/activity`)
      .send({ action: "printed" });

    expect(res.status).toBe(400); // not a 500 from the database
  });

  it("adds a document, lists it, archives, deletes, and cascades activity", async () => {
    const up = (await request(app).post("/uploads").set("Content-Type", "application/pdf").set("x-file-name", "q1.pdf").send(Buffer.from("pdf"))).body;
    const doc = (await request(app).post(`/folders/${folderId}/documents`).send({ name: "Q1.pdf", upload_id: up.id, size: "3", ext: "pdf" })).body;
    expect(doc.company_id).toBeTruthy();

    const list = await request(app).get(`/folders/${folderId}/documents`);
    expect(list.body.map((d: { id: string }) => d.id)).toEqual([doc.id]);

    // Activity append + read.
    await request(app).post(`/documents/${doc.id}/activity`).send({ action: "download" }).expect(201);
    expect((await request(app).get(`/documents/${doc.id}/activity`)).body.length).toBe(1);

    // Archive → excluded from default list; still visible with include_archived.
    await request(app).post(`/documents/${doc.id}/archive`).expect(200);
    expect((await request(app).get(`/folders/${folderId}/documents`)).body.length).toBe(0);
    expect((await request(app).get(`/folders/${folderId}/documents?include_archived=true`)).body.length).toBe(1);

    // Delete → gone, and activity cascaded.
    await request(app).delete(`/documents/${doc.id}`).expect(204);
    expect((await db.select().from(schema.documents)).length).toBe(0);
    expect((await db.select().from(schema.documentActivity)).length).toBe(0);
  });

  describe("folder grants are enforced on the server", () => {
    const BUYER: SessionUser = { ...BROKER, id: randomUUID(), role: "buyer" };

    /** The buyer, in whatever company beforeEach just created. */
    const asBuyer = (): SessionUser => ({
      ...BUYER,
      company_id: current.company_id,
      company_ids: current.company_ids,
    });

    /** folder_access.user_id is a real FK; a grant needs a real person. */
    async function seedUser(id: string): Promise<string> {
      await client.query(
        `INSERT INTO users (id, name, email, password_hash, role, company_id)
         VALUES ($1,'Someone',$2,'x','buyer',(SELECT company_id FROM folders WHERE id=$3))
         ON CONFLICT (id) DO NOTHING`,
        [id, `${id}@x.test`, folderId],
      );
      return id;
    }

    async function grantTo(folder: string, subject: { user?: string; group?: string }, perms = {}) {
      const p = { read: true, write: false, download: false, ...perms };
      // created_by is NOT NULL in the deployed schema — the fixture obeys the
      // same constraints the access panel does.
      await client.query(
        `INSERT INTO folder_access (folder_id, user_id, group_id, can_read, can_write, can_download, created_by)
         VALUES ($1,$2,$3,$4,$5,$6,$7)`,
        [folder, subject.user ?? null, subject.group ?? null, p.read, p.write, p.download, BROKER.id],
      );
    }

    it("leaves an ungranted folder open, exactly as before", async () => {
      // Every folder in the product is ungranted. Denying here would empty the
      // data room on the first deploy rather than tighten an existing rule.
      await seedDocument();
      current = asBuyer();

      expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(200);
    });

    it("shuts out a buyer nobody granted, once the folder is configured", async () => {
      // The defect: this returned 200 with the full document list, because the
      // guard only ever checked company membership.
      await seedDocument();
      await grantTo(folderId, { user: await seedUser(randomUUID()) });
      current = asBuyer();

      expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(403);
    });

    it("lets a granted buyer in", async () => {
      await seedDocument();
      await grantTo(folderId, { user: await seedUser(BUYER.id) });
      current = asBuyer();

      expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(200);
    });

    it("reaches a buyer through a group", async () => {
      await seedDocument();
      const group = randomUUID();
      await client.query(
        `INSERT INTO buyer_groups (id, company_id, name) VALUES ($1, (SELECT company_id FROM folders WHERE id=$2), 'Bidder A')`,
        [group, folderId],
      );
      await seedUser(BUYER.id);
      await client.query(
        `INSERT INTO buyer_group_members (group_id, user_id) VALUES ($1,$2)`,
        [group, BUYER.id],
      );
      await grantTo(folderId, { group });
      current = asBuyer();

      expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(200);
    });

    it("separates read from write", async () => {
      // The whole point of three capabilities: a buyer who may look at a folder
      // is not thereby allowed to put things in it.
      const up = (await request(app).post("/uploads").set("Content-Type", "application/pdf")
        .set("x-file-name", "x.pdf").send(Buffer.from("pdf"))).body;
      await grantTo(folderId, { user: await seedUser(BUYER.id) }, { read: true, write: false });
      current = asBuyer();

      expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(200);
      const created = await request(app).post(`/folders/${folderId}/documents`)
        .send({ name: "Sneaky.pdf", upload_id: up.id, size: "3", ext: "pdf" });
      expect(created.status).toBe(403);
    });

    it("does not let a restricted folder be walked around by addressing the document", async () => {
      const documentId = await seedDocument();
      await grantTo(folderId, { user: await seedUser(randomUUID()) });
      current = asBuyer();

      expect((await request(app).get(`/documents/${documentId}/activity`)).status).toBe(403);
    });

    it("never gates the broker who owns the room", async () => {
      await seedDocument();
      await grantTo(folderId, { user: await seedUser(randomUUID()) });

      expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(200);
    });
  });

  it("400s a malformed document create and blocks cross-tenant access (403)", async () => {
    expect((await request(app).post(`/folders/${folderId}/documents`).send({ name: "x" })).status).toBe(400);
    current = { ...BROKER, role: "buyer", company_ids: [randomUUID()] };
    expect((await request(app).get(`/folders/${folderId}/documents`)).status).toBe(403);
  });
});

/**
 * Only the uploader's id reached the client, and the file explorer has no user
 * directory to resolve it against — so every document in the data room read
 * "Uploaded by: Unknown". In a product whose value proposition is provenance,
 * that is the one field that must never be blank.
 */
describe("uploads router — a document says who uploaded it", () => {
  it("returns the uploader's name alongside the id", async () => {
    const up = (await request(app).post("/uploads")
      .set("Content-Type", "application/pdf").set("x-file-name", "ledger.pdf")
      .send(Buffer.from("pdf"))).body;
    await request(app)
      .post(`/folders/${folderId}/documents`)
      .send({ name: "Ledger.pdf", upload_id: up.id, size: "3", ext: "pdf" })
      .expect(201);

    const listed = await request(app).get(`/folders/${folderId}/documents`).expect(200);
    const doc = listed.body[0];

    expect(doc.uploaded_by).toBe(BROKER.id);
    expect(doc.uploaded_by_name).toBe(BROKER.name);
    expect(doc.uploaded_by_name).not.toBe("Unknown");
  });
});
