import { useCallback, useEffect, useMemo, useState } from "react";
import {
  RefreshCw,
  Loader2,
  ListTree,
  ChevronDown,
  ChevronRight,
  Check,
  X,
  Pencil,
} from "lucide-react";
import {
  getChartOfAccounts,
  regenerateChartOfAccounts,
  updateChartOfAccount,
} from "../../lib/api";

const STATEMENT_LABELS = {
  balance_sheet: "Balance Sheet",
  profit_loss: "Profit & Loss",
};

/**
 * Read/review UI for a Key Report version's Chart of Accounts.
 * The COA is generated by Sync; this panel shows the hierarchy, lets the user
 * regenerate it, and supports light inline editing (rename / activate-deactivate).
 */
export default function ChartOfAccountsPanel({ versionId, hasSyncedData, notify }) {
  const [tree, setTree] = useState([]);
  const [accountCount, setAccountCount] = useState(0);
  const [loading, setLoading] = useState(false);
  const [regenerating, setRegenerating] = useState(false);
  const [collapsed, setCollapsed] = useState({});
  const [editingId, setEditingId] = useState(null);
  const [editName, setEditName] = useState("");

  const load = useCallback(async () => {
    if (!versionId) {
      setTree([]);
      setAccountCount(0);
      return;
    }
    setLoading(true);
    try {
      const res = await getChartOfAccounts(versionId);
      setTree(res?.tree || []);
      setAccountCount(res?.accountCount || 0);
    } catch (e) {
      notify?.(e.message || "Failed to load Chart of Accounts.", "error");
      setTree([]);
      setAccountCount(0);
    } finally {
      setLoading(false);
    }
  }, [versionId, notify]);

  useEffect(() => {
    load();
  }, [load]);

  const handleRegenerate = async () => {
    if (!versionId) return;
    setRegenerating(true);
    try {
      const res = await regenerateChartOfAccounts(versionId);
      setTree(res?.tree || []);
      setAccountCount(res?.accountCount || 0);
      notify?.("Chart of Accounts regenerated.", "success");
    } catch (e) {
      notify?.(e.message || "Failed to regenerate Chart of Accounts.", "error");
    } finally {
      setRegenerating(false);
    }
  };

  const toggleGroup = (id) =>
    setCollapsed((prev) => ({ ...prev, [id]: !prev[id] }));

  const startEdit = (account) => {
    setEditingId(account.id);
    setEditName(account.accountName);
  };

  const cancelEdit = () => {
    setEditingId(null);
    setEditName("");
  };

  const saveEdit = async (account) => {
    const name = editName.trim();
    if (!name || name === account.accountName) {
      cancelEdit();
      return;
    }
    try {
      await updateChartOfAccount(account.id, { accountName: name });
      cancelEdit();
      await load();
    } catch (e) {
      notify?.(e.message || "Failed to update account.", "error");
    }
  };

  const toggleActive = async (account) => {
    try {
      await updateChartOfAccount(account.id, { isActive: !account.isActive });
      await load();
    } catch (e) {
      notify?.(e.message || "Failed to update account.", "error");
    }
  };

  const leafCount = useMemo(
    () => tree.reduce((sum, g) => sum + (g.children?.length || 0), 0),
    [tree],
  );

  return (
    <div className="mt-4 rounded-2xl border border-border bg-white p-4">
      <div className="mb-3 flex flex-wrap items-center justify-between gap-2">
        <div className="flex items-center gap-2">
          <ListTree size={16} className="text-primary" />
          <h3 className="text-sm font-bold text-text-primary">Chart of Accounts</h3>
          {leafCount > 0 && (
            <span className="rounded-full bg-bg-page px-2 py-0.5 text-xs text-text-muted">
              {leafCount} account{leafCount === 1 ? "" : "s"}
            </span>
          )}
        </div>
        <button
          onClick={handleRegenerate}
          disabled={regenerating || !hasSyncedData}
          title={hasSyncedData ? "Rebuild from this version's GL data" : "Run Sync first to generate the Chart of Accounts"}
          className="flex items-center gap-1.5 rounded-lg border border-border px-2.5 py-1.5 text-xs font-semibold text-text-primary hover:bg-bg-page disabled:opacity-50"
        >
          {regenerating ? <Loader2 size={13} className="animate-spin" /> : <RefreshCw size={13} />}
          Regenerate
        </button>
      </div>

      {loading ? (
        <div className="flex items-center gap-2 py-8 text-sm text-text-muted">
          <Loader2 size={15} className="animate-spin" /> Loading…
        </div>
      ) : accountCount === 0 ? (
        <p className="py-6 text-center text-xs text-text-muted">
          {hasSyncedData
            ? "No accounts found. Try Regenerate."
            : "Sync a version with General Ledger or Balance Sheet files to build the Chart of Accounts."}
        </p>
      ) : (
        <div className="space-y-3">
          {tree.map((group) => {
            const isCollapsed = collapsed[group.id];
            const children = group.children || [];
            if (!children.length) return null;
            return (
              <div key={group.id || group.accountName} className="rounded-xl border border-border">
                <button
                  onClick={() => toggleGroup(group.id)}
                  className="flex w-full items-center gap-2 rounded-t-xl bg-bg-page px-3 py-2 text-left"
                >
                  {isCollapsed ? <ChevronRight size={14} /> : <ChevronDown size={14} />}
                  <span className="text-sm font-semibold text-text-primary">{group.accountName}</span>
                  <span className="ml-2 rounded-full bg-white px-2 py-0.5 text-[11px] text-text-muted">
                    {STATEMENT_LABELS[group.statementType] || group.statementType || ""}
                  </span>
                  <span className="ml-auto text-xs text-text-muted">{children.length}</span>
                </button>
                {!isCollapsed && (
                  <ul className="divide-y divide-border">
                    {children.map((acct) => (
                      <li
                        key={acct.id}
                        className={`flex items-center gap-2 px-3 py-1.5 text-sm ${
                          acct.isActive ? "" : "opacity-50"
                        }`}
                      >
                        {acct.accountNumber && (
                          <span className="w-16 shrink-0 font-mono text-xs text-text-muted">
                            {acct.accountNumber}
                          </span>
                        )}
                        {editingId === acct.id ? (
                          <>
                            <input
                              autoFocus
                              value={editName}
                              onChange={(e) => setEditName(e.target.value)}
                              onKeyDown={(e) => {
                                if (e.key === "Enter") saveEdit(acct);
                                if (e.key === "Escape") cancelEdit();
                              }}
                              className="flex-1 rounded border border-primary px-2 py-0.5 text-sm"
                            />
                            <button onClick={() => saveEdit(acct)} className="rounded p-1 text-primary hover:bg-bg-page" title="Save">
                              <Check size={14} />
                            </button>
                            <button onClick={cancelEdit} className="rounded p-1 text-text-muted hover:bg-bg-page" title="Cancel">
                              <X size={14} />
                            </button>
                          </>
                        ) : (
                          <>
                            <span className="flex-1 truncate text-text-primary" title={acct.accountName}>
                              {acct.accountName}
                            </span>
                            <span className="rounded bg-bg-page px-1.5 py-0.5 text-[11px] capitalize text-text-muted">
                              {acct.accountType}
                            </span>
                            <button
                              onClick={() => startEdit(acct)}
                              className="rounded p-1 text-text-muted hover:bg-bg-page hover:text-text-primary"
                              title="Rename"
                            >
                              <Pencil size={13} />
                            </button>
                            <button
                              onClick={() => toggleActive(acct)}
                              className="rounded px-1.5 py-0.5 text-[11px] font-semibold text-text-muted hover:bg-bg-page"
                              title={acct.isActive ? "Mark inactive" : "Mark active"}
                            >
                              {acct.isActive ? "Active" : "Inactive"}
                            </button>
                          </>
                        )}
                      </li>
                    ))}
                  </ul>
                )}
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
