-- CIM question library — GENERATED, do not edit by hand.
--
-- Source: FIELD_LABEL_OVERRIDES and SECTION_QUESTION_BANK in
-- apps/web/src/pages/broker/workspace/WorkspaceCimPrep.jsx, which already held
-- several hundred authored questions bound to the blocks they fill.
--
-- Regenerate: node tools/demo/extract-cim-questions.mjs > tools/demo/seed-cim-questions.sql

BEGIN;

DELETE FROM cim_question_library WHERE scope = 'system';

INSERT INTO cim_question_library (scope, section_key, layout_key, block_key_pattern, question_text, help_text, sort_order) VALUES
  ('system', 'executive-summary', 'source-slide-05', '5:11:token:1', 'What is the company''s current market share (%)?', NULL, 1),
  ('system', 'executive-summary', 'source-slide-05', '5:11:token:2', 'Which market or industry segment does the company operate in?', NULL, 2),
  ('system', 'executive-summary', 'source-slide-05', '5:11:token:3', 'What is the company''s current market ranking (e.g., #1, Top 3, #4)?', NULL, 3),
  ('system', 'executive-summary', 'source-slide-05', '5:11:token:4', 'Which geography, region, or market does this ranking and market share apply to?', NULL, 4),
  ('system', 'executive-summary', 'source-slide-05', '5:16:token:0', 'What percentage of the company''s revenue is recurring or contractual?', NULL, 5),
  ('system', 'executive-summary', 'source-slide-05', '5:21:token:0', 'What is the combined industry experience of the company''s leadership team (in years)?', NULL, 6),
  ('system', 'executive-summary', 'source-slide-05', '5:26:token:0', 'What is the company''s gross margin (%)?', NULL, 7),
  ('system', 'executive-summary', 'source-slide-05', '5:26:token:1', 'What is the company''s EBITDA margin (%)?', NULL, 8),
  ('system', 'executive-summary', 'source-slide-06', '6:6:token:0', 'Do these metrics represent Trailing Twelve Months (TTM) or a Fiscal Year (FY)?', 'Options: Trailing Twelve Months (TTM); Fiscal Year (FY)', 9),
  ('system', 'executive-summary', 'source-slide-06', '6:6:token:1', 'What is the reporting date (as of)?', NULL, 10),
  ('system', 'executive-summary', 'source-slide-06', '6:9:token:0', 'What is the company''s total revenue (in USD millions)?', NULL, 11),
  ('system', 'executive-summary', 'source-slide-06', '6:11:token:0', 'What is the year-over-year (YoY) revenue growth (%)?', NULL, 12),
  ('system', 'executive-summary', 'source-slide-06', '6:14:token:0', 'What is the current gross margin (%)?', NULL, 13),
  ('system', 'executive-summary', 'source-slide-06', '6:16:token:0', 'How many percentage points has the gross margin changed vs. the prior year?', NULL, 14),
  ('system', 'executive-summary', 'source-slide-06', '6:19:token:0', 'What is the company''s EBITDA (in USD millions)?', NULL, 15),
  ('system', 'executive-summary', 'source-slide-06', '6:21:token:0', 'What is the company''s EBITDA margin (%)?', NULL, 16),
  ('system', 'executive-summary', 'source-slide-06', '6:24:token:0', 'What is the company''s current revenue multiple (x)?', NULL, 17),
  ('system', 'executive-summary', 'source-slide-06', '6:26:token:0', 'What is the comparable revenue multiple range (min-max x)?', NULL, 18),
  ('system', 'executive-summary', 'source-slide-06', '6:31:token:0', 'What is the company''s revenue CAGR (%)?', NULL, 19),
  ('system', 'executive-summary', 'source-slide-06', '6:31:token:1', 'Which financial years does this CAGR cover?', NULL, 20),
  ('system', 'executive-summary', 'source-slide-06', '6:31:token:2', 'How many percentage points has the EBITDA margin improved?', NULL, 21),
  ('system', 'executive-summary', 'source-slide-06', '6:31:token:3', 'What is the primary growth driver?', NULL, 22),
  ('system', 'company-overview', 'source-slide-08', '8:5:token:2', 'Which customer segment does the company primarily serve?', NULL, 23),
  ('system', 'company-overview', 'source-slide-08', '8:5:token:3', 'Which geography or region does the company primarily operate in?', NULL, 24),
  ('system', 'company-overview', 'source-slide-08', '8:6:token:1', 'In which year was the company founded?', NULL, 25),
  ('system', 'company-overview', 'source-slide-08', '8:16:token:0', 'How many employees does the company have?', NULL, 26),
  ('system', 'company-overview', 'source-slide-08', '8:20:token:0', 'How many customers or clients does the company serve?', NULL, 27),
  ('system', 'company-overview', 'source-slide-08', '8:24:token:0', 'Where is the company''s headquarters located (City, Country)?', NULL, 28),
  ('system', 'company-overview', 'source-slide-08', '8:28:token:0', 'What is the company''s legal structure or entity type?', NULL, 29),
  ('system', 'company-overview', 'source-slide-09', '9:5:token:2', 'How many years has the company been in operation?', NULL, 30),
  ('system', 'company-overview', 'source-slide-09', '9:34:token:0', 'What is the company''s current annual revenue (in USD millions)?', NULL, 31),
  ('system', 'company-overview', 'source-slide-09', '9:36:token:0', 'What is the company''s current EBITDA margin (%)?', NULL, 32),
  ('system', 'company-overview', 'source-slide-09', '9:38:token:0', 'How many active customers does the company currently have?', NULL, 33),
  ('system', 'company-overview', 'source-slide-09', '9:40:token:0', 'How many products or SKUs does the company currently offer?', NULL, 34),
  ('system', 'company-overview', 'source-slide-09', '9:42:token:0', 'How many full-time employees (FTEs) does the company currently have?', NULL, 35),
  ('system', 'company-overview', 'source-slide-10', '10:6:token:0', 'As of what date does this legal structure and ownership chart apply?', NULL, 36),
  ('system', 'products-services', 'source-slide-12', '12:5:token:1', 'How many core products or services are offered?', NULL, 37),
  ('system', 'products-services', 'source-slide-12', '12:5:token:2', 'How many product or service categories are offered?', NULL, 38),
  ('system', 'products-services', 'source-slide-12', '12:5:token:3', 'Which customer profiles use these offerings?', NULL, 39),
  ('system', 'products-services', 'source-slide-12', '12:6:token:0', 'What customer outcome does the portfolio deliver?', NULL, 40),
  ('system', 'products-services', 'source-slide-12', '12:6:token:1', 'How has the offering portfolio evolved?', NULL, 41),
  ('system', 'products-services', 'source-slide-12', '12:6:token:2', 'How was the portfolio developed or expanded?', NULL, 42),
  ('system', 'products-services', 'source-slide-12', '12:11:token:0', 'What is the first product or service name?', NULL, 43),
  ('system', 'products-services', 'source-slide-12', '12:12:token:0', 'Which category does the first offering belong to?', NULL, 44),
  ('system', 'products-services', 'source-slide-12', '12:14:token:0', 'What is first offering ARR (USD millions)?', NULL, 45),
  ('system', 'products-services', 'source-slide-12', '12:15:token:0', 'What revenue share comes from the first offering (%)?', NULL, 46),
  ('system', 'products-services', 'source-slide-12', '12:17:token:0', 'What right-side revenue metric applies to first offering (%)?', NULL, 47),
  ('system', 'products-services', 'source-slide-12', '12:23:token:0', 'What is the second product or service name?', NULL, 48),
  ('system', 'products-services', 'source-slide-12', '12:24:token:0', 'Which category does the second offering belong to?', NULL, 49),
  ('system', 'products-services', 'source-slide-12', '12:26:token:0', 'What is second offering ARR (USD millions)?', NULL, 50),
  ('system', 'products-services', 'source-slide-12', '12:27:token:0', 'What revenue share comes from the second offering (%)?', NULL, 51),
  ('system', 'products-services', 'source-slide-12', '12:29:token:0', 'What right-side revenue metric applies to second offering (%)?', NULL, 52),
  ('system', 'products-services', 'source-slide-12', '12:35:token:0', 'What is the third product or service name?', NULL, 53),
  ('system', 'products-services', 'source-slide-12', '12:36:token:0', 'Which category does the third offering belong to?', NULL, 54),
  ('system', 'products-services', 'source-slide-12', '12:38:token:0', 'What is third offering ARR (USD millions)?', NULL, 55),
  ('system', 'products-services', 'source-slide-12', '12:39:token:0', 'What revenue share comes from the third offering (%)?', NULL, 56),
  ('system', 'products-services', 'source-slide-12', '12:41:token:0', 'What right-side revenue metric applies to third offering (%)?', NULL, 57),
  ('system', 'products-services', 'source-slide-12', '12:43:token:0', 'What period ending date supports this product data?', NULL, 58),
  ('system', 'products-services', 'source-slide-13', '13:5:token:1', 'Which key dimensions differentiate the company?', NULL, 59),
  ('system', 'products-services', 'source-slide-13', '13:6:token:0', 'Which competitors or alternatives are being compared?', NULL, 60),
  ('system', 'products-services', 'source-slide-13', '13:9:token:0', 'What is the first differentiator?', NULL, 61),
  ('system', 'products-services', 'source-slide-13', '13:10:token:0', 'Why does the first differentiator matter?', NULL, 62),
  ('system', 'products-services', 'source-slide-13', '13:13:token:0', 'What is the second differentiator?', NULL, 63),
  ('system', 'products-services', 'source-slide-13', '13:14:token:0', 'Why does the second differentiator matter?', NULL, 64),
  ('system', 'products-services', 'source-slide-13', '13:17:token:0', 'What is the third differentiator?', NULL, 65),
  ('system', 'products-services', 'source-slide-13', '13:18:token:0', 'Why does the third differentiator matter?', NULL, 66),
  ('system', 'products-services', 'source-slide-13', '13:21:token:0', 'What is the fourth differentiator?', NULL, 67),
  ('system', 'products-services', 'source-slide-13', '13:22:token:0', 'Why does the fourth differentiator matter?', NULL, 68),
  ('system', 'products-services', 'source-slide-13', '13:23:token:0', 'What source supports these differentiators?', NULL, 69),
  ('system', 'management-team', 'source-slide-15', '15:5:token:1', 'What is combined management experience in years?', NULL, 70),
  ('system', 'management-team', 'source-slide-15', '15:6:token:0', 'What capability has management demonstrated?', NULL, 71),
  ('system', 'management-team', 'source-slide-15', '15:10:token:0', 'What is the first executive''s full name?', NULL, 72),
  ('system', 'management-team', 'source-slide-15', '15:11:token:0', 'What is the first executive''s title?', NULL, 73),
  ('system', 'management-team', 'source-slide-15', '15:12:token:0', 'How many years of experience does the first executive have?', NULL, 74),
  ('system', 'management-team', 'source-slide-15', '15:18:token:0', 'What is the second executive''s full name?', NULL, 75),
  ('system', 'management-team', 'source-slide-15', '15:19:token:0', 'What is the second executive''s title?', NULL, 76),
  ('system', 'management-team', 'source-slide-15', '15:20:token:0', 'How many years of experience does the second executive have?', NULL, 77),
  ('system', 'management-team', 'source-slide-15', '15:26:token:0', 'What is the third executive''s full name?', NULL, 78),
  ('system', 'management-team', 'source-slide-15', '15:27:token:0', 'What is the third executive''s title?', NULL, 79),
  ('system', 'management-team', 'source-slide-15', '15:28:token:0', 'How many years of experience does the third executive have?', NULL, 80),
  ('system', 'management-team', 'source-slide-15', '15:34:token:0', 'What is the fourth executive''s full name?', NULL, 81),
  ('system', 'management-team', 'source-slide-15', '15:35:token:0', 'What is the fourth executive''s title?', NULL, 82),
  ('system', 'management-team', 'source-slide-15', '15:36:token:0', 'How many years of experience does the fourth executive have?', NULL, 83),
  ('system', 'management-team', 'source-slide-15', '15:39:token:0', 'What source supports the management bios?', NULL, 84),
  ('system', 'market-overview', 'source-slide-17', '17:5:token:0', 'What is the relevant market name?', NULL, 85),
  ('system', 'market-overview', 'source-slide-17', '17:5:token:1', 'What is the addressable market size (USD billions)?', NULL, 86),
  ('system', 'market-overview', 'source-slide-17', '17:5:token:2', 'What is the market CAGR (%)?', NULL, 87),
  ('system', 'market-overview', 'source-slide-17', '17:5:token:3', 'What key tailwinds drive market growth?', NULL, 88),
  ('system', 'market-overview', 'source-slide-17', '17:6:token:0', 'Which primary growth driver applies to this market?', NULL, 89),
  ('system', 'market-overview', 'source-slide-17', '17:9:token:0', 'What is TAM size (USD billions)?', NULL, 90),
  ('system', 'market-overview', 'source-slide-17', '17:11:token:0', 'Which year is the TAM estimate for?', NULL, 91),
  ('system', 'market-overview', 'source-slide-17', '17:14:token:0', 'What is serviceable market size (USD billions)?', NULL, 92),
  ('system', 'market-overview', 'source-slide-17', '17:16:token:0', 'Which geography or segment defines this market?', NULL, 93),
  ('system', 'market-overview', 'source-slide-17', '17:19:token:0', 'What is the market growth rate (%)?', NULL, 94),
  ('system', 'market-overview', 'source-slide-17', '17:21:token:0', 'What is the market CAGR base year?', NULL, 95),
  ('system', 'market-overview', 'source-slide-17', '17:21:token:1', 'What is the market CAGR forecast year?', NULL, 96),
  ('system', 'market-overview', 'source-slide-17', '17:24:token:0', 'How many competitors operate in this market?', NULL, 97),
  ('system', 'market-overview', 'source-slide-17', '17:31:token:0', 'Which market research source supports this data?', NULL, 98),
  ('system', 'market-overview', 'source-slide-17', '17:31:token:1', 'What year was the market source published?', NULL, 99),
  ('system', 'market-overview', 'source-slide-18', '18:5:token:1', 'How is the company positioned versus competitors?', NULL, 100),
  ('system', 'market-overview', 'source-slide-18', '18:5:token:2', 'What key dimension differentiates the company?', NULL, 101),
  ('system', 'market-overview', 'source-slide-18', '18:6:token:1', 'What is the first positioning matrix dimension?', NULL, 102),
  ('system', 'market-overview', 'source-slide-18', '18:6:token:2', 'What is the second positioning matrix dimension?', NULL, 103),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:1', 'What is the company''s size (USD millions)?', NULL, 104),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:2', 'What is the company''s key differentiation?', NULL, 105),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:3', 'What is the first competitor''s name?', NULL, 106),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:4', 'What is the first competitor''s size (USD millions)?', NULL, 107),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:6', 'What is the second competitor''s name?', NULL, 108),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:7', 'What is the second competitor''s size (USD millions)?', NULL, 109),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:9', 'What is the third competitor''s name?', NULL, 110),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:10', 'What is the third competitor''s size (USD millions)?', NULL, 111),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:12', 'What is the fourth competitor''s name?', NULL, 112),
  ('system', 'market-overview', 'source-slide-18', '18:10:token:13', 'What is the fourth competitor''s size (USD millions)?', NULL, 113),
  ('system', 'market-overview', 'source-slide-18', '18:11:token:0', 'What year supports the competitive analysis?', NULL, 114),
  ('system', 'operations', 'source-slide-20', '20:5:token:1', 'What is the company''s primary revenue model?', NULL, 115),
  ('system', 'operations', 'source-slide-20', '20:6:token:0', 'What operating characteristic defines the model?', NULL, 116),
  ('system', 'operations', 'source-slide-20', '20:6:token:1', 'What gross margin does the model generate (%)?', NULL, 117),
  ('system', 'operations', 'source-slide-20', '20:9:token:0', 'What is the first revenue stream?', NULL, 118),
  ('system', 'operations', 'source-slide-20', '20:10:token:0', 'What revenue share comes from the first stream (%)?', NULL, 119),
  ('system', 'operations', 'source-slide-20', '20:16:token:0', 'What is the second revenue stream?', NULL, 120),
  ('system', 'operations', 'source-slide-20', '20:17:token:0', 'What revenue share comes from the second stream (%)?', NULL, 121),
  ('system', 'operations', 'source-slide-20', '20:23:token:0', 'What is the third revenue stream?', NULL, 122),
  ('system', 'operations', 'source-slide-20', '20:24:token:0', 'What revenue share comes from the third stream (%)?', NULL, 123),
  ('system', 'operations', 'source-slide-20', '20:28:token:0', 'What period supports the revenue model data?', NULL, 124),
  ('system', 'operations', 'source-slide-21', '21:5:token:1', 'What key characteristic defines the operating model?', NULL, 125),
  ('system', 'operations', 'source-slide-21', '21:10:token:0', 'What is average operational cycle time in days?', NULL, 126),
  ('system', 'operations', 'source-slide-21', '21:13:token:0', 'What is current utilization rate (%)?', NULL, 127),
  ('system', 'operations', 'source-slide-21', '21:16:token:0', 'How many FTEs support operations?', NULL, 128),
  ('system', 'operations', 'source-slide-21', '21:19:token:0', 'How many platforms support operations?', NULL, 129),
  ('system', 'operations', 'source-slide-21', '21:21:token:0', 'What source supports the operations data?', NULL, 130),
  ('system', 'financial-performance', 'source-slide-23', '23:5:token:1', 'What is the company''s revenue CAGR (%)?', NULL, 131),
  ('system', 'financial-performance', 'source-slide-23', '23:5:token:3', 'What was the EBITDA margin at the beginning of this period (%)?', NULL, 132),
  ('system', 'financial-performance', 'source-slide-23', '23:5:token:4', 'What is the current EBITDA margin (%)?', NULL, 133),
  ('system', 'financial-performance', 'source-slide-23', '23:6:token:0', 'What are the primary factors driving the company''s financial performance?', NULL, 134),
  ('system', 'financial-performance', 'source-slide-23', '23:9:token:0', 'What is the company''s revenue for the selected financial year?', NULL, 135),
  ('system', 'financial-performance', 'source-slide-23', '23:10:token:0', 'Which financial year does this revenue correspond to?', NULL, 136),
  ('system', 'financial-performance', 'source-slide-23', '23:11:token:0', 'What was the company''s revenue in the previous financial year?', NULL, 137),
  ('system', 'financial-performance', 'source-slide-23', '23:11:token:1', 'Which is the previous financial year (FY-1)?', NULL, 138),
  ('system', 'financial-performance', 'source-slide-23', '23:14:token:0', 'What is the company''s current gross margin (%)?', NULL, 139),
  ('system', 'financial-performance', 'source-slide-23', '23:16:token:0', 'What was the company''s gross margin in the previous financial year (%)?', NULL, 140),
  ('system', 'financial-performance', 'source-slide-23', '23:16:token:1', 'Which is the previous financial year (FY-1)?', NULL, 141),
  ('system', 'financial-performance', 'source-slide-23', '23:19:token:0', 'What is the company''s EBITDA?', NULL, 142),
  ('system', 'financial-performance', 'source-slide-23', '23:21:token:0', 'What is the company''s EBITDA margin (%)?', NULL, 143),
  ('system', 'financial-performance', 'source-slide-23', '23:24:token:0', 'What is the company''s Free Cash Flow?', NULL, 144),
  ('system', 'financial-performance', 'source-slide-23', '23:26:token:0', 'What is the company''s Free Cash Flow (FCF) conversion (%)?', NULL, 145),
  ('system', 'financial-performance', 'source-slide-23', '23:29:token:0', 'What is the company''s Net Debt / EBITDA ratio (x)?', NULL, 146),
  ('system', 'financial-performance', 'source-slide-23', '23:31:token:0', 'As of what date does this ratio apply?', NULL, 147),
  ('system', 'financial-performance', 'source-slide-23', '23:36:token:2', 'Which accounting firm audited these financial statements?', NULL, 148),
  ('system', 'financial-performance', 'source-slide-24', '24:5:token:0', 'What is the first financial year shown?', NULL, 149),
  ('system', 'financial-performance', 'source-slide-24', '24:5:token:1', 'What is the last financial year shown?', NULL, 150),
  ('system', 'financial-performance', 'source-slide-24', '24:6:token:0', 'Which accounting basis are figures presented on?', NULL, 151),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:0', 'Which fiscal year is FY[Y-3]?', NULL, 152),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:1', 'Which fiscal year is FY[Y-2]?', NULL, 153),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:2', 'Which fiscal year is FY[Y-1]?', NULL, 154),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:3', 'Which fiscal year is FY[Y]?', NULL, 155),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:4', 'What is the LTM period end date?', NULL, 156),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:5', 'What was revenue in FY[Y-3]?', NULL, 157),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:6', 'What was revenue in FY[Y-2]?', NULL, 158),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:7', 'What was revenue in FY[Y-1]?', NULL, 159),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:8', 'What was revenue in FY[Y]?', NULL, 160),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:9', 'What was revenue for LTM?', NULL, 161),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:10', 'What was YoY revenue growth in FY[Y-3]?', NULL, 162),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:11', 'What was YoY revenue growth in FY[Y-2]?', NULL, 163),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:12', 'What was YoY revenue growth in FY[Y-1]?', NULL, 164),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:13', 'What was YoY revenue growth in FY[Y]?', NULL, 165),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:14', 'What was cost of goods sold in FY[Y-3]?', NULL, 166),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:15', 'What was cost of goods sold in FY[Y-2]?', NULL, 167),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:16', 'What was cost of goods sold in FY[Y-1]?', NULL, 168),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:17', 'What was cost of goods sold in FY[Y]?', NULL, 169),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:18', 'What was cost of goods sold for LTM?', NULL, 170),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:19', 'What was gross profit in FY[Y-3]?', NULL, 171),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:20', 'What was gross profit in FY[Y-2]?', NULL, 172),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:21', 'What was gross profit in FY[Y-1]?', NULL, 173),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:22', 'What was gross profit in FY[Y]?', NULL, 174),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:23', 'What was gross profit for LTM?', NULL, 175),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:24', 'What was gross margin in FY[Y-3]?', NULL, 176),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:25', 'What was gross margin in FY[Y-2]?', NULL, 177),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:26', 'What was gross margin in FY[Y-1]?', NULL, 178),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:27', 'What was gross margin in FY[Y]?', NULL, 179),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:28', 'What was gross margin for LTM?', NULL, 180),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:29', 'What were SG&A expenses in FY[Y-3]?', NULL, 181),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:30', 'What were SG&A expenses in FY[Y-2]?', NULL, 182),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:31', 'What were SG&A expenses in FY[Y-1]?', NULL, 183),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:32', 'What were SG&A expenses in FY[Y]?', NULL, 184),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:33', 'What were SG&A expenses for LTM?', NULL, 185),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:34', 'What was EBITDA in FY[Y-3]?', NULL, 186),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:35', 'What was EBITDA in FY[Y-2]?', NULL, 187),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:36', 'What was EBITDA in FY[Y-1]?', NULL, 188),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:37', 'What was EBITDA in FY[Y]?', NULL, 189),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:38', 'What was EBITDA for LTM?', NULL, 190),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:39', 'What was EBITDA margin in FY[Y-3]?', NULL, 191),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:40', 'What was EBITDA margin in FY[Y-2]?', NULL, 192),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:41', 'What was EBITDA margin in FY[Y-1]?', NULL, 193),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:42', 'What was EBITDA margin in FY[Y]?', NULL, 194),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:43', 'What was EBITDA margin for LTM?', NULL, 195),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:44', 'What was depreciation and amortization in FY[Y-3]?', NULL, 196),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:45', 'What was depreciation and amortization in FY[Y-2]?', NULL, 197),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:46', 'What was depreciation and amortization in FY[Y-1]?', NULL, 198),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:47', 'What was depreciation and amortization in FY[Y]?', NULL, 199),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:48', 'What was depreciation and amortization for LTM?', NULL, 200),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:49', 'What was EBIT in FY[Y-3]?', NULL, 201),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:50', 'What was EBIT in FY[Y-2]?', NULL, 202),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:51', 'What was EBIT in FY[Y-1]?', NULL, 203),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:52', 'What was EBIT in FY[Y]?', NULL, 204),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:53', 'What was EBIT for LTM?', NULL, 205),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:54', 'What was net income in FY[Y-3]?', NULL, 206),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:55', 'What was net income in FY[Y-2]?', NULL, 207),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:56', 'What was net income in FY[Y-1]?', NULL, 208),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:57', 'What was net income in FY[Y]?', NULL, 209),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:58', 'What was net income for LTM?', NULL, 210),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:59', 'What was CapEx in FY[Y-3]?', NULL, 211),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:60', 'What was CapEx in FY[Y-2]?', NULL, 212),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:61', 'What was CapEx in FY[Y-1]?', NULL, 213),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:62', 'What was CapEx in FY[Y]?', NULL, 214),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:63', 'What was CapEx for LTM?', NULL, 215),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:64', 'What was Free Cash Flow in FY[Y-3]?', NULL, 216),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:65', 'What was Free Cash Flow in FY[Y-2]?', NULL, 217),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:66', 'What was Free Cash Flow in FY[Y-1]?', NULL, 218),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:67', 'What was Free Cash Flow in FY[Y]?', NULL, 219),
  ('system', 'financial-performance', 'source-slide-24', '24:7:token:68', 'What was Free Cash Flow for LTM?', NULL, 220),
  ('system', 'financial-performance', 'source-slide-25', '25:5:token:0', 'What is adjusted EBITDA (USD millions)?', NULL, 221),
  ('system', 'financial-performance', 'source-slide-25', '25:5:token:1', 'How many EBITDA add-backs are included?', NULL, 222),
  ('system', 'financial-performance', 'source-slide-25', '25:5:token:2', 'What is total add-backs value (USD millions)?', NULL, 223),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:0', 'What is reported EBITDA (USD millions)?', NULL, 224),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:1', 'What is owner compensation normalization (USD thousands)?', NULL, 225),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:2', 'What are one-time legal and advisory fees (USD thousands)?', NULL, 226),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:3', 'What is non-cash stock compensation (USD thousands)?', NULL, 227),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:4', 'What is related-party transaction adjustment (USD thousands)?', NULL, 228),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:5', 'What is restructuring or severance adjustment (USD thousands)?', NULL, 229),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:6', 'What are other one-time items (USD thousands)?', NULL, 230),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:7', 'What is adjusted EBITDA after add-backs (USD millions)?', NULL, 231),
  ('system', 'financial-performance', 'source-slide-25', '25:10:token:8', 'What is adjusted EBITDA margin (%)?', NULL, 232),
  ('system', 'financial-performance', 'source-slide-26', '26:5:token:0', 'What is the balance sheet date?', NULL, 233),
  ('system', 'financial-performance', 'source-slide-26', '26:5:token:1', 'What are total assets (USD millions)?', NULL, 234),
  ('system', 'financial-performance', 'source-slide-26', '26:5:token:2', 'How would you describe the capital structure?', NULL, 235),
  ('system', 'financial-performance', 'source-slide-26', '26:6:token:0', 'What balance sheet quality does the company reflect?', NULL, 236),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:0', 'Which fiscal year is the FY[Y-2]A column?', NULL, 237),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:1', 'Which fiscal year is the FY[Y-1]A column?', NULL, 238),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:2', 'Which fiscal year is the FY[Y]A column?', NULL, 239),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:3', 'What is the LTM balance sheet date?', NULL, 240),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:4', 'What were cash and equivalents in FY[Y-2]?', NULL, 241),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:5', 'What were cash and equivalents in FY[Y-1]?', NULL, 242),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:6', 'What were cash and equivalents in FY[Y]?', NULL, 243),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:7', 'What were cash and equivalents for LTM?', NULL, 244),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:8', 'What were accounts receivable in FY[Y-2]?', NULL, 245),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:9', 'What were accounts receivable in FY[Y-1]?', NULL, 246),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:10', 'What were accounts receivable in FY[Y]?', NULL, 247),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:11', 'What were accounts receivable for LTM?', NULL, 248),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:12', 'What was inventory in FY[Y-2]?', NULL, 249),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:13', 'What was inventory in FY[Y-1]?', NULL, 250),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:14', 'What was inventory in FY[Y]?', NULL, 251),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:15', 'What was inventory for LTM?', NULL, 252),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:16', 'What were prepaid and other current assets in FY[Y-2]?', NULL, 253),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:17', 'What were prepaid and other current assets in FY[Y-1]?', NULL, 254),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:18', 'What were prepaid and other current assets in FY[Y]?', NULL, 255),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:19', 'What were prepaid and other current assets for LTM?', NULL, 256),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:20', 'What were total current assets in FY[Y-2]?', NULL, 257),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:21', 'What were total current assets in FY[Y-1]?', NULL, 258),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:22', 'What were total current assets in FY[Y]?', NULL, 259),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:23', 'What were total current assets for LTM?', NULL, 260),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:24', 'What was net PP&E in FY[Y-2]?', NULL, 261),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:25', 'What was net PP&E in FY[Y-1]?', NULL, 262),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:26', 'What was net PP&E in FY[Y]?', NULL, 263),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:27', 'What was net PP&E for LTM?', NULL, 264),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:28', 'What were intangibles and goodwill in FY[Y-2]?', NULL, 265),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:29', 'What were intangibles and goodwill in FY[Y-1]?', NULL, 266),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:30', 'What were intangibles and goodwill in FY[Y]?', NULL, 267),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:31', 'What were intangibles and goodwill for LTM?', NULL, 268),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:32', 'What were total assets in FY[Y-2]?', NULL, 269),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:33', 'What were total assets in FY[Y-1]?', NULL, 270),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:34', 'What were total assets in FY[Y]?', NULL, 271),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:35', 'What were total assets for LTM?', NULL, 272),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:36', 'What were accounts payable in FY[Y-2]?', NULL, 273),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:37', 'What were accounts payable in FY[Y-1]?', NULL, 274),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:38', 'What were accounts payable in FY[Y]?', NULL, 275),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:39', 'What were accounts payable for LTM?', NULL, 276),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:40', 'What were accrued liabilities in FY[Y-2]?', NULL, 277),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:41', 'What were accrued liabilities in FY[Y-1]?', NULL, 278),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:42', 'What were accrued liabilities in FY[Y]?', NULL, 279),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:43', 'What were accrued liabilities for LTM?', NULL, 280),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:44', 'What was deferred revenue in FY[Y-2]?', NULL, 281),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:45', 'What was deferred revenue in FY[Y-1]?', NULL, 282),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:46', 'What was deferred revenue in FY[Y]?', NULL, 283),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:47', 'What was deferred revenue for LTM?', NULL, 284),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:48', 'What was current portion of debt in FY[Y-2]?', NULL, 285),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:49', 'What was current portion of debt in FY[Y-1]?', NULL, 286),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:50', 'What was current portion of debt in FY[Y]?', NULL, 287),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:51', 'What was current portion of debt for LTM?', NULL, 288),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:52', 'What were total current liabilities in FY[Y-2]?', NULL, 289),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:53', 'What were total current liabilities in FY[Y-1]?', NULL, 290),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:54', 'What were total current liabilities in FY[Y]?', NULL, 291),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:55', 'What were total current liabilities for LTM?', NULL, 292),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:56', 'What was long-term debt in FY[Y-2]?', NULL, 293),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:57', 'What was long-term debt in FY[Y-1]?', NULL, 294),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:58', 'What was long-term debt in FY[Y]?', NULL, 295),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:59', 'What was long-term debt for LTM?', NULL, 296),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:60', 'What was total shareholders'' equity in FY[Y-2]?', NULL, 297),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:61', 'What was total shareholders'' equity in FY[Y-1]?', NULL, 298),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:62', 'What was total shareholders'' equity in FY[Y]?', NULL, 299),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:63', 'What was total shareholders'' equity for LTM?', NULL, 300),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:64', 'What were total liabilities and equity in FY[Y-2]?', NULL, 301),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:65', 'What were total liabilities and equity in FY[Y-1]?', NULL, 302),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:66', 'What were total liabilities and equity in FY[Y]?', NULL, 303),
  ('system', 'financial-performance', 'source-slide-26', '26:7:token:67', 'What were total liabilities and equity for LTM?', NULL, 304),
  ('system', 'financial-performance', 'source-slide-26', '26:8:token:0', 'What is the first audited financial year?', NULL, 305),
  ('system', 'financial-performance', 'source-slide-26', '26:8:token:1', 'What is the last audited financial year?', NULL, 306),
  ('system', 'financial-performance', 'source-slide-27', '27:5:token:0', 'What is cumulative free cash flow (USD millions)?', NULL, 307),
  ('system', 'financial-performance', 'source-slide-27', '27:5:token:1', 'Which financial years does cumulative FCF cover?', NULL, 308),
  ('system', 'financial-performance', 'source-slide-27', '27:6:token:0', 'What is free cash flow conversion (%)?', NULL, 309),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:0', 'Which fiscal year is the FY[Y-2]A column?', NULL, 310),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:1', 'Which fiscal year is the FY[Y-1]A column?', NULL, 311),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:2', 'Which fiscal year is the FY[Y]A column?', NULL, 312),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:3', 'What is the LTM cash flow date?', NULL, 313),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:4', 'What was net income in FY[Y-2]?', NULL, 314),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:5', 'What was net income in FY[Y-1]?', NULL, 315),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:6', 'What was net income in FY[Y]?', NULL, 316),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:7', 'What was net income for LTM?', NULL, 317),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:8', 'What was D&A in FY[Y-2]?', NULL, 318),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:9', 'What was D&A in FY[Y-1]?', NULL, 319),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:10', 'What was D&A in FY[Y]?', NULL, 320),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:11', 'What was D&A for LTM?', NULL, 321),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:12', 'What was change in working capital in FY[Y-2]?', NULL, 322),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:13', 'What was change in working capital in FY[Y-1]?', NULL, 323),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:14', 'What was change in working capital in FY[Y]?', NULL, 324),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:15', 'What was change in working capital for LTM?', NULL, 325),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:16', 'What were other non-cash items in FY[Y-2]?', NULL, 326),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:17', 'What were other non-cash items in FY[Y-1]?', NULL, 327),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:18', 'What were other non-cash items in FY[Y]?', NULL, 328),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:19', 'What were other non-cash items for LTM?', NULL, 329),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:20', 'What was cash from operations in FY[Y-2]?', NULL, 330),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:21', 'What was cash from operations in FY[Y-1]?', NULL, 331),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:22', 'What was cash from operations in FY[Y]?', NULL, 332),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:23', 'What was cash from operations for LTM?', NULL, 333),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:24', 'What were capital expenditures in FY[Y-2]?', NULL, 334),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:25', 'What were capital expenditures in FY[Y-1]?', NULL, 335),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:26', 'What were capital expenditures in FY[Y]?', NULL, 336),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:27', 'What were capital expenditures for LTM?', NULL, 337),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:28', 'What were acquisitions or dispositions in FY[Y-2]?', NULL, 338),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:29', 'What were acquisitions or dispositions in FY[Y-1]?', NULL, 339),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:30', 'What were acquisitions or dispositions in FY[Y]?', NULL, 340),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:31', 'What were acquisitions or dispositions for LTM?', NULL, 341),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:32', 'What was cash from investing in FY[Y-2]?', NULL, 342),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:33', 'What was cash from investing in FY[Y-1]?', NULL, 343),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:34', 'What was cash from investing in FY[Y]?', NULL, 344),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:35', 'What was cash from investing for LTM?', NULL, 345),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:36', 'What were net borrowings or repayments in FY[Y-2]?', NULL, 346),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:37', 'What were net borrowings or repayments in FY[Y-1]?', NULL, 347),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:38', 'What were net borrowings or repayments in FY[Y]?', NULL, 348),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:39', 'What were net borrowings or repayments for LTM?', NULL, 349),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:40', 'What were dividends or distributions in FY[Y-2]?', NULL, 350),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:41', 'What were dividends or distributions in FY[Y-1]?', NULL, 351),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:42', 'What were dividends or distributions in FY[Y]?', NULL, 352),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:43', 'What were dividends or distributions for LTM?', NULL, 353),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:44', 'What was cash from financing in FY[Y-2]?', NULL, 354),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:45', 'What was cash from financing in FY[Y-1]?', NULL, 355),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:46', 'What was cash from financing in FY[Y]?', NULL, 356),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:47', 'What was cash from financing for LTM?', NULL, 357),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:48', 'What was net change in cash in FY[Y-2]?', NULL, 358),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:49', 'What was net change in cash in FY[Y-1]?', NULL, 359),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:50', 'What was net change in cash in FY[Y]?', NULL, 360),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:51', 'What was net change in cash for LTM?', NULL, 361),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:52', 'What was free cash flow in FY[Y-2]?', NULL, 362),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:53', 'What was free cash flow in FY[Y-1]?', NULL, 363),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:54', 'What was free cash flow in FY[Y]?', NULL, 364),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:55', 'What was free cash flow for LTM?', NULL, 365),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:56', 'What was FCF conversion in FY[Y-2]?', NULL, 366),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:57', 'What was FCF conversion in FY[Y-1]?', NULL, 367),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:58', 'What was FCF conversion in FY[Y]?', NULL, 368),
  ('system', 'financial-performance', 'source-slide-27', '27:7:token:59', 'What was FCF conversion for LTM?', NULL, 369),
  ('system', 'financial-performance', 'source-slide-28', '28:5:token:0', 'What is average net working capital (USD millions)?', NULL, 370),
  ('system', 'financial-performance', 'source-slide-28', '28:5:token:1', 'How many trailing months are measured?', NULL, 371),
  ('system', 'financial-performance', 'source-slide-28', '28:5:token:2', 'What is the NWC cycle in days?', NULL, 372),
  ('system', 'financial-performance', 'source-slide-28', '28:6:token:0', 'How seasonal is net working capital?', NULL, 373),
  ('system', 'financial-performance', 'source-slide-28', '28:6:token:1', 'Which quarter has peak working capital?', NULL, 374),
  ('system', 'financial-performance', 'source-slide-28', '28:6:token:2', 'What drives peak working capital?', NULL, 375),
  ('system', 'financial-performance', 'source-slide-28', '28:9:token:0', 'What is current net working capital (USD millions)?', NULL, 376),
  ('system', 'financial-performance', 'source-slide-28', '28:11:token:0', 'What is target NWC at close (USD millions)?', NULL, 377),
  ('system', 'financial-performance', 'source-slide-28', '28:14:token:0', 'What is days sales outstanding (DSO)?', NULL, 378),
  ('system', 'financial-performance', 'source-slide-28', '28:16:token:0', 'What is industry average DSO?', NULL, 379),
  ('system', 'financial-performance', 'source-slide-28', '28:19:token:0', 'What is days payable outstanding (DPO)?', NULL, 380),
  ('system', 'financial-performance', 'source-slide-28', '28:21:token:0', 'What is industry average DPO?', NULL, 381),
  ('system', 'financial-performance', 'source-slide-28', '28:24:token:0', 'What are inventory days?', NULL, 382),
  ('system', 'financial-performance', 'source-slide-28', '28:26:token:0', 'What working capital notes should be shown?', NULL, 383),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:0', 'Which fiscal year is the FY[Y]A column?', NULL, 384),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:1', 'What were accounts receivable in FY[Y]?', NULL, 385),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:2', 'What were accounts receivable for LTM?', NULL, 386),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:3', 'What was inventory in FY[Y]?', NULL, 387),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:4', 'What was inventory for LTM?', NULL, 388),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:5', 'What were prepaid and other assets in FY[Y]?', NULL, 389),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:6', 'What were prepaid and other assets for LTM?', NULL, 390),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:7', 'What were current assets in FY[Y]?', NULL, 391),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:8', 'What were current assets for LTM?', NULL, 392),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:9', 'What were accounts payable in FY[Y]?', NULL, 393),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:10', 'What were accounts payable for LTM?', NULL, 394),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:11', 'What were accrued liabilities in FY[Y]?', NULL, 395),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:12', 'What were accrued liabilities for LTM?', NULL, 396),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:13', 'What was deferred revenue in FY[Y]?', NULL, 397),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:14', 'What was deferred revenue for LTM?', NULL, 398),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:15', 'What were current liabilities in FY[Y]?', NULL, 399),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:16', 'What were current liabilities for LTM?', NULL, 400),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:17', 'What was net working capital in FY[Y]?', NULL, 401),
  ('system', 'financial-performance', 'source-slide-28', '28:30:token:18', 'What was net working capital for LTM?', NULL, 402),
  ('system', 'financial-performance', 'source-slide-29', '29:6:token:0', 'What is the reconciliation date?', NULL, 403),
  ('system', 'financial-performance', 'source-slide-29', '29:9:token:0', 'What is book GL cash balance (USD millions)?', NULL, 404),
  ('system', 'financial-performance', 'source-slide-29', '29:14:token:0', 'What is bank statement cash balance (USD millions)?', NULL, 405),
  ('system', 'financial-performance', 'source-slide-29', '29:16:token:0', 'Which bank statement supports the balance?', NULL, 406),
  ('system', 'financial-performance', 'source-slide-29', '29:16:token:1', 'What is the bank statement date?', NULL, 407),
  ('system', 'financial-performance', 'source-slide-29', '29:19:token:0', 'What are unresolved reconciling items (USD thousands)?', NULL, 408),
  ('system', 'financial-performance', 'source-slide-29', '29:21:token:0', 'How many reconciling items were identified?', NULL, 409),
  ('system', 'financial-performance', 'source-slide-29', '29:26:token:0', 'Who prepared the bank reconciliation?', NULL, 410),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:0', 'What is book GL cash balance (USD millions)?', NULL, 411),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:1', 'What deposits in transit remain (USD thousands)?', NULL, 412),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:2', 'When did deposits in transit clear?', NULL, 413),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:3', 'What outstanding cheques remain (USD thousands)?', NULL, 414),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:4', 'When did outstanding cheques clear?', NULL, 415),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:5', 'What bank charges were not recorded (USD thousands)?', NULL, 416),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:6', 'What interest remains unrecorded (USD thousands)?', NULL, 417),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:7', 'What other reconciling items remain (USD thousands)?', NULL, 418),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:8', 'What is the status of other reconciling items?', NULL, 419),
  ('system', 'financial-performance', 'source-slide-29', '29:28:token:9', 'What is bank statement balance (USD millions)?', NULL, 420),
  ('system', 'financial-performance', 'source-slide-29', '29:32:token:0', 'Which bank provided the source statement?', NULL, 421),
  ('system', 'financial-performance', 'source-slide-29', '29:32:token:1', 'What is the bank statement source date?', NULL, 422),
  ('system', 'financial-performance', 'source-slide-29', '29:32:token:2', 'What is the general ledger date?', NULL, 423),
  ('system', 'financial-performance', 'source-slide-29', '29:32:token:3', 'Who prepared the source reconciliation?', NULL, 424),
  ('system', 'financial-performance', 'source-slide-30', '30:5:token:0', 'What is the effective tax rate (%)?', NULL, 425),
  ('system', 'financial-performance', 'source-slide-30', '30:6:token:0', 'Which accounting firm prepares tax filings?', NULL, 426),
  ('system', 'financial-performance', 'source-slide-30', '30:9:token:0', 'What is the current effective tax rate (%)?', NULL, 427),
  ('system', 'financial-performance', 'source-slide-30', '30:11:token:0', 'What is the statutory tax rate (%)?', NULL, 428),
  ('system', 'financial-performance', 'source-slide-30', '30:14:token:0', 'What is current tax provision (USD millions)?', NULL, 429),
  ('system', 'financial-performance', 'source-slide-30', '30:16:token:0', 'What date applies to current tax provision?', NULL, 430),
  ('system', 'financial-performance', 'source-slide-30', '30:19:token:0', 'What is deferred tax balance (USD millions)?', NULL, 431),
  ('system', 'financial-performance', 'source-slide-30', '30:21:token:0', 'What date applies to deferred tax balance?', NULL, 432),
  ('system', 'financial-performance', 'source-slide-30', '30:24:token:0', 'Which tax year is currently open?', NULL, 433),
  ('system', 'financial-performance', 'source-slide-30', '30:26:token:0', 'Which tax jurisdiction is relevant?', NULL, 434),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:0', 'Which fiscal year is the FY[Y-1]A column?', NULL, 435),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:1', 'Which fiscal year is the FY[Y]A column?', NULL, 436),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:2', 'What was pre-tax income in FY[Y-1]?', NULL, 437),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:3', 'What was pre-tax income in FY[Y]?', NULL, 438),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:4', 'What was pre-tax income for LTM?', NULL, 439),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:5', 'What was statutory tax rate in FY[Y-1]?', NULL, 440),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:6', 'What was statutory tax rate in FY[Y]?', NULL, 441),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:7', 'What was statutory tax rate for LTM?', NULL, 442),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:8', 'What was tax at statutory rate in FY[Y-1]?', NULL, 443),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:9', 'What was tax at statutory rate in FY[Y]?', NULL, 444),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:10', 'What was tax at statutory rate for LTM?', NULL, 445),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:11', 'What were non-deductible expenses in FY[Y-1]?', NULL, 446),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:12', 'What were non-deductible expenses in FY[Y]?', NULL, 447),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:13', 'What were non-deductible expenses for LTM?', NULL, 448),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:14', 'What were tax credits or incentives in FY[Y-1]?', NULL, 449),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:15', 'What were tax credits or incentives in FY[Y]?', NULL, 450),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:16', 'What were tax credits or incentives for LTM?', NULL, 451),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:17', 'What were temporary differences in FY[Y-1]?', NULL, 452),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:18', 'What were temporary differences in FY[Y]?', NULL, 453),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:19', 'What were temporary differences for LTM?', NULL, 454),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:20', 'What were other tax adjustments in FY[Y-1]?', NULL, 455),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:21', 'What were other tax adjustments in FY[Y]?', NULL, 456),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:22', 'What were other tax adjustments for LTM?', NULL, 457),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:23', 'What was current tax provision in FY[Y-1]?', NULL, 458),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:24', 'What was current tax provision in FY[Y]?', NULL, 459),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:25', 'What was current tax provision for LTM?', NULL, 460),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:26', 'What was effective tax rate in FY[Y-1]?', NULL, 461),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:27', 'What was effective tax rate in FY[Y]?', NULL, 462),
  ('system', 'financial-performance', 'source-slide-30', '30:28:token:28', 'What was effective tax rate for LTM?', NULL, 463),
  ('system', 'financial-performance', 'source-slide-30', '30:31:token:1', 'Which tax years remain open to audit?', NULL, 464),
  ('system', 'financial-performance', 'source-slide-30', '30:32:token:0', 'What is the first tax return year?', NULL, 465),
  ('system', 'financial-performance', 'source-slide-30', '30:32:token:1', 'What is the last tax return year?', NULL, 466),
  ('system', 'financial-performance', 'source-slide-30', '30:32:token:2', 'Who is the tax advisor?', NULL, 467),
  ('system', 'financial-performance', 'source-slide-30', '30:32:token:3', 'What date confirms no open assessments?', NULL, 468),
  ('system', 'financial-projections', 'source-slide-32', '32:5:token:1', 'What is projected revenue (USD millions)?', NULL, 469),
  ('system', 'financial-projections', 'source-slide-32', '32:5:token:2', 'What is the target projection fiscal year?', NULL, 470),
  ('system', 'financial-projections', 'source-slide-32', '32:5:token:3', 'What is projected revenue CAGR (%)?', NULL, 471),
  ('system', 'financial-projections', 'source-slide-32', '32:5:token:4', 'What is target EBITDA margin (%)?', NULL, 472),
  ('system', 'financial-projections', 'source-slide-32', '32:6:token:0', 'What key macro assumption underpins projections?', NULL, 473),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:0', 'Which fiscal year is the base year?', NULL, 474),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:1', 'Which fiscal year is projection year one?', NULL, 475),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:2', 'Which fiscal year is projection year two?', NULL, 476),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:3', 'Which fiscal year is projection year three?', NULL, 477),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:4', 'Which fiscal year is projection year four?', NULL, 478),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:5', 'What is projected revenue in FY[Y]A (Base)?', NULL, 479),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:6', 'What is projected revenue in FY[Y+1]E?', NULL, 480),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:7', 'What is projected revenue in FY[Y+2]E?', NULL, 481),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:8', 'What is projected revenue in FY[Y+3]E?', NULL, 482),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:9', 'What is projected revenue in FY[Y+4]E?', NULL, 483),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:10', 'What is projected YoY revenue growth in FY[Y+1]E?', NULL, 484),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:11', 'What is projected YoY revenue growth in FY[Y+2]E?', NULL, 485),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:12', 'What is projected YoY revenue growth in FY[Y+3]E?', NULL, 486),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:13', 'What is projected YoY revenue growth in FY[Y+4]E?', NULL, 487),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:14', 'What is projected gross profit in FY[Y]A (Base)?', NULL, 488),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:15', 'What is projected gross profit in FY[Y+1]E?', NULL, 489),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:16', 'What is projected gross profit in FY[Y+2]E?', NULL, 490),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:17', 'What is projected gross profit in FY[Y+3]E?', NULL, 491),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:18', 'What is projected gross profit in FY[Y+4]E?', NULL, 492),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:19', 'What is projected gross margin in FY[Y]A (Base)?', NULL, 493),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:20', 'What is projected gross margin in FY[Y+1]E?', NULL, 494),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:21', 'What is projected gross margin in FY[Y+2]E?', NULL, 495),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:22', 'What is projected gross margin in FY[Y+3]E?', NULL, 496),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:23', 'What is projected gross margin in FY[Y+4]E?', NULL, 497),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:24', 'What is projected EBITDA in FY[Y]A (Base)?', NULL, 498),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:25', 'What is projected EBITDA in FY[Y+1]E?', NULL, 499),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:26', 'What is projected EBITDA in FY[Y+2]E?', NULL, 500),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:27', 'What is projected EBITDA in FY[Y+3]E?', NULL, 501),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:28', 'What is projected EBITDA in FY[Y+4]E?', NULL, 502),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:29', 'What is projected EBITDA margin in FY[Y]A (Base)?', NULL, 503),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:30', 'What is projected EBITDA margin in FY[Y+1]E?', NULL, 504),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:31', 'What is projected EBITDA margin in FY[Y+2]E?', NULL, 505),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:32', 'What is projected EBITDA margin in FY[Y+3]E?', NULL, 506),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:33', 'What is projected EBITDA margin in FY[Y+4]E?', NULL, 507),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:34', 'What is projected free cash flow in FY[Y]A (Base)?', NULL, 508),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:35', 'What is projected free cash flow in FY[Y+1]E?', NULL, 509),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:36', 'What is projected free cash flow in FY[Y+2]E?', NULL, 510),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:37', 'What is projected free cash flow in FY[Y+3]E?', NULL, 511),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:38', 'What is projected free cash flow in FY[Y+4]E?', NULL, 512),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:39', 'What is projected CapEx in FY[Y]A (Base)?', NULL, 513),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:40', 'What is projected CapEx in FY[Y+1]E?', NULL, 514),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:41', 'What is projected CapEx in FY[Y+2]E?', NULL, 515),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:42', 'What is projected CapEx in FY[Y+3]E?', NULL, 516),
  ('system', 'financial-projections', 'source-slide-32', '32:7:token:43', 'What is projected CapEx in FY[Y+4]E?', NULL, 517),
  ('system', 'financial-projections', 'source-slide-33', '33:10:token:0', 'What is the organic revenue growth assumption (%)?', NULL, 518),
  ('system', 'financial-projections', 'source-slide-33', '33:14:token:0', 'What is the projected minimum gross margin (%)?', NULL, 519),
  ('system', 'financial-projections', 'source-slide-33', '33:14:token:1', 'What is the projected maximum gross margin (%)?', NULL, 520),
  ('system', 'financial-projections', 'source-slide-33', '33:18:token:0', 'What is starting EBITDA margin (%)?', NULL, 521),
  ('system', 'financial-projections', 'source-slide-33', '33:18:token:1', 'What is ending EBITDA margin (%)?', NULL, 522),
  ('system', 'financial-projections', 'source-slide-33', '33:22:token:0', 'What is minimum annual CapEx (USD millions)?', NULL, 523),
  ('system', 'financial-projections', 'source-slide-33', '33:22:token:1', 'What is maximum annual CapEx (USD millions)?', NULL, 524),
  ('system', 'financial-projections', 'source-slide-33', '33:26:token:0', 'What are expected NWC days?', NULL, 525),
  ('system', 'financial-projections', 'source-slide-33', '33:30:token:0', 'What is the first downside risk?', NULL, 526),
  ('system', 'financial-projections', 'source-slide-33', '33:30:token:1', 'What is the second downside risk?', NULL, 527),
  ('system', 'growth-strategy', 'source-slide-35', '35:5:token:1', 'How many organic growth levers are identified?', NULL, 528),
  ('system', 'growth-strategy', 'source-slide-35', '35:5:token:2', 'What is the post-close execution timeline?', NULL, 529),
  ('system', 'growth-strategy', 'source-slide-35', '35:10:token:0', 'What is the first growth initiative?', NULL, 530),
  ('system', 'growth-strategy', 'source-slide-35', '35:12:token:0', 'What is first initiative impact (USD millions)?', NULL, 531),
  ('system', 'growth-strategy', 'source-slide-35', '35:17:token:0', 'What is the second growth initiative?', NULL, 532),
  ('system', 'growth-strategy', 'source-slide-35', '35:19:token:0', 'What margin improvement does initiative two deliver (%)?', NULL, 533),
  ('system', 'growth-strategy', 'source-slide-35', '35:24:token:0', 'What is the third growth initiative?', NULL, 534),
  ('system', 'growth-strategy', 'source-slide-35', '35:26:token:0', 'What is third initiative impact (USD millions)?', NULL, 535),
  ('system', 'growth-strategy', 'source-slide-35', '35:31:token:0', 'What is the fourth growth initiative?', NULL, 536),
  ('system', 'growth-strategy', 'source-slide-35', '35:33:token:0', 'What multiple impact does initiative four deliver (x)?', NULL, 537),
  ('system', 'transaction-overview', 'source-slide-37', '37:5:token:1', 'What buyer type is being targeted?', NULL, 538),
  ('system', 'transaction-overview', 'source-slide-37', '37:6:token:0', 'What transaction type is contemplated?', NULL, 539),
  ('system', 'transaction-overview', 'source-slide-37', '37:6:token:1', 'What consideration structure is contemplated?', NULL, 540),
  ('system', 'transaction-overview', 'source-slide-37', '37:6:token:2', 'Is the consideration structure available or contemplated?', NULL, 541),
  ('system', 'transaction-overview', 'source-slide-37', '37:10:token:0', 'What transaction structure should be shown?', NULL, 542),
  ('system', 'transaction-overview', 'source-slide-37', '37:14:token:0', 'What ownership percentage or control level is offered?', NULL, 543),
  ('system', 'transaction-overview', 'source-slide-37', '37:18:token:0', 'What consideration mix should be shown?', NULL, 544),
  ('system', 'transaction-overview', 'source-slide-37', '37:22:token:0', 'What financing or regulatory conditions apply?', NULL, 545),
  ('system', 'transaction-overview', 'source-slide-37', '37:26:token:0', 'What seller financing amount is available?', NULL, 546),
  ('system', 'transaction-overview', 'source-slide-37', '37:26:token:1', 'What seller financing interest rate applies (%)?', NULL, 547),
  ('system', 'transaction-overview', 'source-slide-37', '37:26:token:2', 'What seller financing term applies in years?', NULL, 548),
  ('system', 'transaction-overview', 'source-slide-37', '37:30:token:0', 'How many months will management remain?', NULL, 549),
  ('system', 'transaction-overview', 'source-slide-37', '37:34:token:0', 'What is the first-round bid date?', NULL, 550),
  ('system', 'transaction-overview', 'source-slide-37', '37:34:token:1', 'What is the LOI due date?', NULL, 551),
  ('system', 'transaction-overview', 'source-slide-37', '37:34:token:2', 'What is the target closing date?', NULL, 552),
  ('system', 'closing', 'source-slide-38', '38:11:token:0', 'What copyright year should appear?', NULL, 553),
  ('system', 'basic-details', NULL, NULL, 'Confirm the legal company name, operating/trade name, headquarters address, website, and primary contact details.', 'Section prompt (company-profile)', 554),
  ('system', 'basic-details', NULL, NULL, 'Confirm the preferred project name and whether it should appear with or without the word Project.', 'Section prompt (project-name)', 555),
  ('system', 'basic-details', NULL, NULL, 'Provide the latest company logo file and any usage guidance for the CIM.', 'Section prompt (company-logo)', 556),
  ('system', 'basic-details', NULL, NULL, 'Provide the advisor logo and preferred advisor contact block for the cover/back pages.', 'Section prompt (advisor-logo)', 557),
  ('system', 'basic-details', NULL, NULL, 'Confirm any confidentiality wording, disclaimers, or recipient restrictions that should be reflected.', 'Section prompt (confidentiality)', 558),
  ('system', 'executive-summary', NULL, NULL, 'List the top investment highlights that a buyer should understand immediately.', 'Section prompt (highlights)', 559),
  ('system', 'executive-summary', NULL, NULL, 'Provide the key financial metrics, operating KPIs, and latest LTM figures to feature.', 'Section prompt (metrics)', 560),
  ('system', 'executive-summary', NULL, NULL, 'Summarize the strategic rationale for the transaction and preferred buyer profile.', 'Section prompt (rationale)', 561),
  ('system', 'executive-summary', NULL, NULL, 'Call out any key risks, sensitivities, or diligence topics the CIM should address carefully.', 'Section prompt (risks)', 562),
  ('system', 'executive-summary', NULL, NULL, 'Provide a concise one-line description of the business and market position.', 'Section prompt (one-liner)', 563),
  ('system', 'company-overview', NULL, NULL, 'Provide the founding story, ownership history, major milestones, and current ownership structure.', 'Section prompt (history)', 564),
  ('system', 'company-overview', NULL, NULL, 'Describe how the company makes money, customer types served, and key revenue streams.', 'Section prompt (business-model)', 565),
  ('system', 'company-overview', NULL, NULL, 'Provide legal entity names, subsidiaries, ownership percentages, and jurisdiction details.', 'Section prompt (legal-structure)', 566),
  ('system', 'company-overview', NULL, NULL, 'List operating locations, served geographies, and any planned expansion regions.', 'Section prompt (geography)', 567),
  ('system', 'company-overview', NULL, NULL, 'Explain what makes the company distinctive versus competitors.', 'Section prompt (differentiation)', 568),
  ('system', 'products-services', NULL, NULL, 'Describe the main products and services, including pricing model and delivery model.', 'Section prompt (offering)', 569),
  ('system', 'products-services', NULL, NULL, 'Provide revenue mix by product/service line and any margin differences by offering.', 'Section prompt (mix)', 570),
  ('system', 'products-services', NULL, NULL, 'Identify the core customer segments, use cases, and buyer decision makers.', 'Section prompt (customers)', 571),
  ('system', 'products-services', NULL, NULL, 'Provide upcoming product/service launches or roadmap items relevant to growth.', 'Section prompt (pipeline)', 572),
  ('system', 'products-services', NULL, NULL, 'Share representative customer wins, case studies, or proof points.', 'Section prompt (case-studies)', 573),
  ('system', 'management-team', NULL, NULL, 'Provide short bios for key management team members, including tenure and prior experience.', 'Section prompt (bios)', 574),
  ('system', 'management-team', NULL, NULL, 'Provide the current organization chart and reporting lines.', 'Section prompt (org-chart)', 575),
  ('system', 'management-team', NULL, NULL, 'Describe management retention plans, succession risks, or key-person dependencies.', 'Section prompt (retention)', 576),
  ('system', 'management-team', NULL, NULL, 'Provide headcount by function, location, and employee/contractor split.', 'Section prompt (headcount)', 577),
  ('system', 'management-team', NULL, NULL, 'Summarize compensation, incentive plans, or equity participation relevant to a buyer.', 'Section prompt (incentives)', 578),
  ('system', 'market-overview', NULL, NULL, 'Provide market size, growth rate, TAM/SAM/SOM, and source references.', 'Section prompt (market-size)', 579),
  ('system', 'market-overview', NULL, NULL, 'List the key industry tailwinds supporting future growth.', 'Section prompt (tailwinds)', 580),
  ('system', 'market-overview', NULL, NULL, 'Identify key competitors and how the company is positioned against them.', 'Section prompt (competitive-landscape)', 581),
  ('system', 'market-overview', NULL, NULL, 'Provide market segmentation by geography, customer type, product, or channel.', 'Section prompt (segmentation)', 582),
  ('system', 'market-overview', NULL, NULL, 'Describe regulatory, technology, or macro trends that may affect the business.', 'Section prompt (regulation)', 583),
  ('system', 'operations', NULL, NULL, 'Describe the end-to-end operating workflow or value chain from lead/source to delivery.', 'Section prompt (process)', 584),
  ('system', 'operations', NULL, NULL, 'List major systems, tools, vendors, facilities, and infrastructure used by the business.', 'Section prompt (systems)', 585),
  ('system', 'operations', NULL, NULL, 'Provide utilization, capacity constraints, service levels, and scalability considerations.', 'Section prompt (capacity)', 586),
  ('system', 'operations', NULL, NULL, 'Identify critical suppliers, partners, dependencies, or concentration risks.', 'Section prompt (suppliers)', 587),
  ('system', 'operations', NULL, NULL, 'Describe quality control, certifications, compliance processes, and operating KPIs.', 'Section prompt (quality)', 588),
  ('system', 'financial-performance', NULL, NULL, 'Provide historical revenue, gross profit, EBITDA, and margin details for the requested periods.', 'Section prompt (historicals)', 589),
  ('system', 'financial-performance', NULL, NULL, 'List EBITDA add-backs, normalizations, and one-time items with support.', 'Section prompt (adjustments)', 590),
  ('system', 'financial-performance', NULL, NULL, 'Explain growth drivers, pricing changes, volume trends, and recurring revenue dynamics.', 'Section prompt (revenue-drivers)', 591),
  ('system', 'financial-performance', NULL, NULL, 'Provide working capital trends, seasonality, and proposed target NWC peg assumptions.', 'Section prompt (working-capital)', 592),
  ('system', 'financial-performance', NULL, NULL, 'Provide bank debt, tax, cash, and other balance sheet items relevant to the transaction.', 'Section prompt (debt-tax)', 593),
  ('system', 'financial-projections', NULL, NULL, 'Provide management forecast by year for revenue, gross profit, EBITDA, capex, and cash flow.', 'Section prompt (forecast)', 594),
  ('system', 'financial-projections', NULL, NULL, 'Explain the key forecast assumptions, growth levers, and margin expansion drivers.', 'Section prompt (assumptions)', 595),
  ('system', 'financial-projections', NULL, NULL, 'Provide downside/upside sensitivities or scenario assumptions if available.', 'Section prompt (scenario)', 596),
  ('system', 'financial-projections', NULL, NULL, 'Provide backlog, pipeline, contracted revenue, or bookings support for the forecast.', 'Section prompt (backlog-pipeline)', 597),
  ('system', 'financial-projections', NULL, NULL, 'Identify investments required to achieve the forecast, including hiring, capex, and systems.', 'Section prompt (investment)', 598),
  ('system', 'growth-strategy', NULL, NULL, 'Describe the primary organic growth initiatives and expected impact.', 'Section prompt (organic)', 599),
  ('system', 'growth-strategy', NULL, NULL, 'Identify geographic expansion opportunities and required investment.', 'Section prompt (geographic)', 600),
  ('system', 'growth-strategy', NULL, NULL, 'Describe product/service expansion opportunities and cross-sell potential.', 'Section prompt (product-expansion)', 601),
  ('system', 'growth-strategy', NULL, NULL, 'List potential acquisition targets, M&A strategy, or consolidation opportunities.', 'Section prompt (ma)', 602),
  ('system', 'growth-strategy', NULL, NULL, 'Identify channel, vendor, or strategic partnerships that can accelerate growth.', 'Section prompt (partnerships)', 603),
  ('system', 'transaction-overview', NULL, NULL, 'Confirm the proposed transaction process, timing, milestones, and diligence expectations.', 'Section prompt (process)', 604),
  ('system', 'transaction-overview', NULL, NULL, 'Provide preferred transaction structure, rollover expectations, and any excluded assets/liabilities.', 'Section prompt (structure)', 605),
  ('system', 'transaction-overview', NULL, NULL, 'Summarize owner objectives, use of proceeds, and post-closing involvement expectations.', 'Section prompt (use-of-proceeds)', 606),
  ('system', 'transaction-overview', NULL, NULL, 'Describe ideal buyer attributes and any buyers that should be included or excluded.', 'Section prompt (buyer-criteria)', 607),
  ('system', 'transaction-overview', NULL, NULL, 'Confirm transaction contacts, data room process, and communication protocol.', 'Section prompt (contacts)', 608);

COMMIT;
